on:
  - pull_request

name: Main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: robinraju/release-downloader@v1.8
        id: download_playnite
        with:
          repository: "JosefNemec/Playnite"
          latest: true
          tarBall: false
          zipBall: false
          fileName: "Playnite*.zip"
          out-file-path: ${{ runner.temp }}/playnite
          extract: true

      - run: |
          dotnet build UpcomingGamesTagger.csproj -c Release
